- hosts: localhost
  connection: local
  become: no
  vars:
    local_user_name: user.name
    github_org_name: GH_org_name
    bitbucket_org_name: BB_org_name
  roles:
    # - config
    - geerlingguy.homebrew
    - fubarhouse.macdock
    - drivers
    - repositories
    - packages
    - chrome_extensions
    - setup_osx
