- hosts: localhost
  connection: local
  become: no
  vars:
    local_user_name: user.name
    github_first_org: GH_org1_name
    github_second_org: GH_org2_name
    # bitbucket_org: BB_org_name
  roles:
    - configs
    - geerlingguy.homebrew
    - fubarhouse.macdock
    - drivers
    - repositories
    - packages
    - chrome_extensions
    - setup_osx
