- name: Create main directory for all repositories
  file:
    path: ~/Documents/repositories
    state: directory
    mode: 0755
  tags:
    - repositories  

- include: github.yml
  tags:
    - repositories  
    - github 

- include: bitbucket.yml
  tags:
    - repositories  
    - bitbucket
