- name: Create main directory for all repositories
  file:
    path: ~/Documents/repositories
    state: directory
    mode: 0755

- name: Create repositories directories
  file:
    path: ~/Documents/repositories/{{ item.name }}
    state: directory
  with_items:
    - "{{ repositories_dir }}"

- name: Clone GitHub repositories
  git:
    repo: git@github.com:{{ github_org_name }}/{{ item.1.name }}.git
    dest: ~/Documents/repositories/{{ item.0.name }}/{{ item.1.name }}
  with_subelements:
    - "{{ repositories_dir }}"
    - repositories
  when: item.0.service == 'GitHub'

- name: Clone BitBucket repositories
  git:
    repo: git@bitbucket.org:{{ bitbucket_org_name }}/{{ item.1.name }}.git
    dest: ~/Documents/repositories/{{ item.0.name }}/{{ item.1.name }}
  with_subelements:
    - "{{ repositories_dir }}"
    - repositories
  when: item.0.service == 'BitBucket'
